### ISSUE TITLE
Error when execute extract_face_from_ibug.py 

### ISSUE THREAD

**Issue by abdou31** [faust690226/cnn-facial-landmark-tutorial#3]
Hello ,
I have organize my data , but when i execute extract_face_from_ibug.py i get this error :
> python extract_face_from_ibug.py

> PTS file numbers: 218597
0%| | 0/218597 [00:00<?, ?it/s]
Traceback (most recent call last):
File "extract_face_from_ibug.py", line 143, in 
main()
File "extract_face_from_ibug.py", line 115, in main
subset_name = head.split('/')[-2]
IndexError: list index out of range

How can i solve this?

**Comment by abdou31** [comment]
I solved my problem , 
If anyone have the same error , click on this link
https://stackoverflow.com/questions/56166760/subset-name-head-split-2-indexerror-list-index-out-of-range/56167136#56167136
